### ISSUE TITLE
ps-cv-pytorch -- pillow 8.3.0 has a bug

### ISSUE THREAD

**Issue by ViitasaariVille** [thoth-station/ps-cv#16]
**Describe the bug**
Pytorch doesn't work correctly with pillow 8.3.0 (https://stackoverflow.com/questions/68223871/pytorch-cifar10-dataset-cannot-get-first-item). Downgrading pillow to 8.2.0 seems to solve the issue.

**To Reproduce**
1. train_data = torchvision.datasets.ImageFolder(root="data/...", transform=TRANSFORM_IMG).

**Comment by pacospace** [comment]
Related-To: https://github.com/python-pillow/Pillow/issues/5571

It seems Pillow team released a patch version that should resolve that issue as well: `8.3.1`

**Comment by pacospace** [comment]
@ViitasaariVille Thanks a lot for opening this issue, after PR linked is merged, we will make a new release of the image!

**Comment by pacospace** [comment]
@ViitasaariVille new image is available https://quay.io/repository/thoth-station/ps-cv-pytorch?tag=v0.1.2&tab=tags with `v0.1.2` tag. Let us know if all works fine now! and thanks once again!

**Comment by ViitasaariVille** [comment]
> @ViitasaariVille new image is available https://quay.io/repository/thoth-station/ps-cv-pytorch?tag=v0.1.2&tab=tags with `v0.1.2` tag. Let us know if all works fine now! and thanks once again!

Works now, many thanks! :)
